### ISSUE TITLE
Module separation WIP

### ISSUE THREAD

**Issue by jonom** [silverstripe/silverstripe-errorpage#1]
Work in progress at https://github.com/silverstripe/silverstripe-errorpage/tree/separation-wip-jonom

Note: I'm happy to re-implement the basic functionality being removed from core, but not planning on making any improvements or fixing any existing bugs in this module, since I don't plan on using it myself. I'll probably publish an alternative to this module in the near future that follows a similar pattern to the Security (login/logout) page content management, which doesn't rely on CMS input.

### To Do
- [x] Set up basic module
- [x] Get tests working
- [x] Work out what to do about namespacing
- [x] Work out what to do about translations
- [x] Link Transifex to module and import existing translations in to Transifex
- [x] Set up Travis integration
- [x] Documentation
- [x] Remove static error page directive from `/silverstripe-assets/templates/SilverStripe/Assets/Flysystem/PublicAssetAdapter_HTAccess.ss`? (Skipped)
- [x] Upgrade instructions for CMS?
- [x] Publish to Composer
- [x] Get [ErrorPage](https://github.com/silverstripe/silverstripe-errorpage/pull/2), [Framework](https://github.com/silverstripe/silverstripe-framework/pull/7061), [CMS](https://github.com/silverstripe/silverstripe-cms/pull/1849) and [Installer](https://github.com/silverstripe/silverstripe-installer/pull/182) PRs merged
- [x] Ping community members who may be interested in maintaining this module or submitting improvements prior to stable release

**Comment by jonom** [comment]
@tractorcow / @flamerohr this module appears to be working fine at the basic level, but I could use some help with a couple of things to wrap it up if you have the time?

### Tests
 tests are bombing currently and I'm not sure how to proceed. Error message is 
> InvalidArgumentException: No fixture definitions found for "=>SilverStripe\Security\Group.admins"

### Namespace
Not sure what namespace to use, or if it even needs changing? Have left unchanged for now.

### Translations
Do these need to be migrated and what would that look like in practice? I don't really know how Transifex works but I know we'd want to preserve the many translations already supplied. I guess if we don't change the namespace, we don't need to change anything about the translations either.... in which case I would modify the CMS PR to not remove any translations.

**Comment by tractorcow** [comment]
SilverStripe\ErrorPage for top level namespace, SilverStripe\ErrorPage\Tests for tests.

Will look at those tests once I'm back from leave.

As far as localisations are concerned, I'm happy for you to leave them to later, but we should at the very least setup the correct keys (make sure you use the correct FQN of the new namespace, not the old one).

**Comment by tractorcow** [comment]
> InvalidArgumentException: No fixture definitions found for "=>SilverStripe\Security\Group.admins"


Because https://github.com/jonom/silverstripe-errorpage/blob/master/tests/model/ErrorPageTest.yml

Has a link to a fixture admin user, but no definition for that user.

The CMS fixture doesn't even have the user fixtures.

https://github.com/silverstripe/silverstripe-cms/blob/d88a7ba54f8d25ff99b478b9cc69d88f523eaef2/tests/model/ErrorPageTest.yml

**Comment by jonom** [comment]
> SilverStripe\ErrorPage for top level namespace

That was my first thought too but thought it might be weird to have the ErrorPage class inside an ErrorPage namespace. Seems to work fine though.

> The CMS fixture doesn't even have the user fixtures.

Yes, I rolled [those in from SiteTreeTest.yml](https://github.com/silverstripe/silverstripe-cms/blob/d88a7ba54f8d25ff99b478b9cc69d88f523eaef2/tests/model/SiteTreeTest.yml#L47-L55), as SiteTreeTest.php used ErrorPage in a couple of tests which I've ported over to ErrorPageTest.php. I removed the EditorGroups entries and the tests pass now, thanks!

> Will look at those tests once I'm back from leave.

Are you on leave now? Sorry for pinging you. Enjoy your time off!

**Comment by jonom** [comment]
Note: I'm now working on https://github.com/silverstripe/silverstripe-errorpage/tree/separation-wip-jonom branch instead of a fork on my own account so it's easier to find.

**Comment by jonom** [comment]
This should be pretty much ready to go now, mainly third party actions left to do like Transifex setup and Packagist listing. I have separated out all of the existing translations and added them to this module and looks like those files can be imported in to Transifex. I'll await your thoughts once you're back from leave @tractorcow.

**Comment by tractorcow** [comment]
@jonom how long are you on leave? If you can I'd like to catch up on skype some time. ;)

**Comment by jonom** [comment]
I thought you were the one on leave 😄 I've sent you a contact request on Skype

**Comment by tractorcow** [comment]
Ah, sorry, I'm back.

Ok see you on skype.

**Comment by tractorcow** [comment]
To do:
 - [ ] Move phpcs.xml.dist to errorpage root
 - [ ] Add lint command to composer.json
 - [ ] copy cms .travis.yml, remove npm and behat (but rest should be ok)
 - [ ] update phpunit to ^5.7

**Comment by tractorcow** [comment]
Add this to `.tx/config`

```
[main]
host = https://www.transifex.com

[silverstripe-errorpage.master]
file_filter = lang/<lang>.yml
source_file = lang/en.yml
source_lang = en
type = YML
```

**Comment by jonom** [comment]
Got Travis tests running eventually, but they're failing due to a class name conflict as you suspected:
> LogicException: Multiple classes ("SilverStripe\CMS\Model\ErrorPage", "SilverStripe\ErrorPage\ErrorPage") map to the same table: "ErrorPage"

**Comment by jonom** [comment]
@tractorcow any thoughts about what to do here? Tests should pass fine after CMS and Framework PRs are merged (they pass locally).

**Comment by jonom** [comment]
@chillu @tractorcow I think this is all basically ready to be merged in time for beta 1 if possible, just need reviews and merge on the various PRs:

* [ErrorPage](https://github.com/silverstripe/silverstripe-errorpage/pull/2)
* [Framework](https://github.com/silverstripe/silverstripe-framework/pull/7061)
* [CMS](https://github.com/silverstripe/silverstripe-cms/pull/1849)
* [Installer](https://github.com/silverstripe/silverstripe-installer/pull/182)

**Comment by chillu** [comment]
>  Link Transifex to module and import existing translations in to Transifex

@tractorcow It looks like either Jono or you have already done that. I can see a lot of translations on https://www.transifex.com/silverstripe/silverstripe-errorpage/dashboard/. Have marked that task as done.

**Comment by jonom** [comment]
@chillu @tractorcow last thing on the to do list is
> Remove static error page directive from /silverstripe-assets/templates/SilverStripe/Assets/Flysystem/PublicAssetAdapter_HTAccess.ss?

Do you have any thoughts on that? I suppose we could remove that part from core and provide an overriding template in this module? Or maybe it's okay to have a little bit of coupling there?

Thanks for pushing this through!

**Comment by tractorcow** [comment]
It doesn't hurt to be there for now; It's mostly benign.

**Comment by jonom** [comment]
Cool all done then!
