### ISSUE TITLE
Where did the icon go 😯

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-errorpage#19]
Well, I know where it went: 

`bundle.css` contains `li.class-ErrorPage>a .jstree-pageicon`. 
It needs to contain `li.class-SilverStripe_ErrorPage_ErrorPage>a .jstree-pageicon` instead.

(.. I don't know where the source of that bundle.css is :-/ and actually, this issue is probably also there for RedirectorPage and, uh, those other built-in ones)

# PRs:

 - [ ] https://github.com/silverstripe/silverstripe-admin/pull/453
 - [ ] https://github.com/silverstripe/silverstripe-cms/pull/2116

**Comment by tractorcow** [comment]
Fixed and PRs in comment at top.

**Comment by tractorcow** [comment]
![image](https://user-images.githubusercontent.com/936064/36954310-f414727c-2085-11e8-9650-87054f7fad50.png)

**Comment by tractorcow** [comment]
We'll need to keep this open until the PRs are merged. :)
