### ISSUE TITLE
Default page contents not translated to German

### ISSUE THREAD

**Issue by bummzack** [silverstripe/silverstripe-errorpage#21]
The default page contents are missing in the German translations (although they were present in 3.x).

Eg: `SilverStripe\ErrorPage\ErrorPage.DEFAULTERRORPAGECONTENT` and `SilverStripe\ErrorPage\ErrorPage.DEFAULTSERVERERRORPAGECONTENT`

I was unable to find this module on Transifex either.

**Comment by maxime-rainville** [comment]
Just added the translation to Transfix. Should filter through in the next release.

https://www.transifex.com/silverstripe/silverstripe-errorpage/translate/#de/master/114471085?q=key%3ADEFAULTERRORPAGECONTENT

**Comment by bummzack** [comment]
Thanks. I wasn't able to find the project over at transifex. Now I requested to join for the german translations. Cheers.
