### ISSUE TITLE
Static error page not regenerated when resources folder gets change

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-errorpage#34]
A side effect of the new configurable resource folder is that your existing static error page won't get regenerated after you change it. That's not an issue when accessing regular routes.

But if looking at a missing file, you get a broken page. 

e.g.: https://www.silverstripe.com/assets/four-zero-four.pdf
![image](https://user-images.githubusercontent.com/1168676/60712905-1b9bf200-9f6c-11e9-9655-7c912a8bc621.png)

# Pull requests
* [x] https://github.com/silverstripe/silverstripe-errorpage/pull/37

**Comment by robbieaverill** [comment]
Fixed with #37
