### ISSUE TITLE
Error page module lacks extensibility

### ISSUE THREAD

**Issue by mfendeksilverstripe** [silverstripe/silverstripe-errorpage#44]
Error page module has following issues with extensibility:

- it uses lot of statically hard coded classes instead of using `Injector`
- error page functionality is available only via inheritance (subclass error page) not composition (extensions)

Content pages are mostly composed from blocks now so it makes sense to have the error page be composed of blocks as well. Subclassing error page and applying all block customisation code may be awkward, a much better approach would be to change error page module to be composition friendly.

This is addressed in Following PR:

https://github.com/silverstripe/silverstripe-errorpage/pull/45

**Comment by dhensby** [comment]
Well this is fixed 🎉 

@mfendeksilverstripe would you mind performing a 1 -> master merge - there have been a few additions and I feel like you're probably best placed to merge these features up into master...

**Comment by mfendeksilverstripe** [comment]
Thanks, I should be able to pick this up within couple of days ;-).

**Comment by mfendeksilverstripe** [comment]
@dhensby This is the merge PR: Pleas double check because it was quite tricky to merge:

https://github.com/silverstripe/silverstripe-errorpage/pull/50

**Comment by dhensby** [comment]
All done! 🎉 thanks!
