### ISSUE TITLE
Error 418 missing

### ISSUE THREAD

**Issue by Firesphere** [silverstripe/silverstripe-errorpage#78]
I can't select error 418 as error code, despite it being a valid and documented error
https://www.rfc-editor.org/rfc/rfc2324#section-2.3.2

As per Wikipedia:
> Sometimes, this status code is also used as a response to a blocked request

**Comment by GuySartorelli** [comment]
Pull requests are welcome.

**Comment by maxime-rainville** [comment]
As much as I'm personally fond of the `418 I'm a tea pot` error code, I think this is likely to cause confusion for content authors.

If there's a legit use case for testing, one could easily add the `418` error code by applying an extension to `ErrorPage` on the `updateCMSField` hook.

**Comment by michalkleiner** [comment]
I would argue here that the module shouldn't filter the list of existing error codes down and exclude some just to appeal to CMS content authors/not to confuse them. It's highly likely they don't understand other codes either and these things are most commonly set up by a vendor anyway and not touched frequently by content editors.

So an extension is ok as a temporary solution, and if there was a PR adding other HTTP error codes not yet covered, I'd support that.
